FROM centos:centos7
MAINTAINER Timothy M. Shead <tshead@sandia.gov>
RUN yum install -y couchdb git zlib-devel bzip2-devel openssl-devel ncurses-devel blas-devel lapack-devel openldap-devel readline-devel tk-devel gcc-c++ libpng-devel hdf5-devel libjpeg-turbo-devel
