import * as React from "react";
import SlycatFormRadioCheckbox from "components/SlycatFormRadioCheckbox";
import SshAuthentication from "components/SshAuthentication";
import type { SshAuthValues } from "utils/remote-auth";

interface RemoteLoginTabProps {
  checked: string;
  onChange: Function;
  loadingData: any;
  onAuthChange: (values: SshAuthValues) => void;
  onAuthEnter?: (values: SshAuthValues) => void;
}

function RemoteLoginTab(props: RemoteLoginTabProps) {
  return (
    <div>
      <div className="alert alert-primary" role="alert">
        Select the data format and job host.
      </div>
      <form className="mb-5">
        <SlycatFormRadioCheckbox
          checked={props.checked === "xyce"}
          onChange={props.onChange}
          value={"xyce"}
          text={"Xyce"}
        />
        <SlycatFormRadioCheckbox
          checked={props.checked === "csv"}
          onChange={props.onChange}
          value={"csv"}
          text={"CSV"}
        />
        <SlycatFormRadioCheckbox
          checked={props.checked === "hdf5"}
          onChange={props.onChange}
          value={"hdf5"}
          text={"Slycat HDF5"}
        />
      </form>
      {props.checked == "hdf5" && (
        <div className="alert alert-primary" role="alert">
          An HDF5 file generated by Slycat from a previous Timeseries model.
        </div>
      )}
      <SshAuthentication
        hostnameMode="locked"
        agent={true}
        loadingData={props.loadingData}
        onChange={props.onAuthChange}
        onEnter={props.onAuthEnter}
      />
    </div>
  );
}

export default RemoteLoginTab;
