ARG IMAGE_VERSION

FROM python:3.7

WORKDIR /usr/src/slycat

COPY requirements.txt ./

RUN apt-get update && apt-get install -y --no-install-recommends \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --no-cache-dir --upgrade pip
RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --no-cache-dir -r requirements.txt

RUN git config --global http.sslVerify false
RUN git config --global http.postBuffer 524288000
RUN git clone --depth 1 https://github.com/sandialabs/slycat.git
RUN mkdir -p /var/lib/slycat/data-store
RUN mkdir -p /var/lib/slycat/data-store/project_data
WORKDIR /usr/src/slycat/slycat
ENV PYTHONPATH "${PYTHONPATH}:/usr/src/slycat/slycat/packages"

CMD python /usr/src/slycat/slycat/web-server/slycat-web-server.py --config /usr/src/slycat/slycat/docker/compose/slycat-compose/slycat-docker-compose-authenticated-config.ini