#!/usr/bin/env python

import requests
import sys

def format_value(value, null=0):
  return value if value is not None else null

if sys.argv[1:2] == ["config"]:
  print "graph_title CouchDB Requests"
  print "graph_category slycat"

  print "request_time_mean.label Request Time (mean)"
  print "request_time_mean.info Average request time over the past 5 minutes."
else:
  try:
    response = requests.get("http://localhost:5984/_stats/couchdb/request_time?length=300", proxies={"http":None}).json()
    print "request_time_mean", format_value(response["couchdb"]["request_time"]["mean"], null="U")
  except:
    print "request_time_mean U"
