#!/usr/bin/env python

import requests
import sys

if sys.argv[1:2] == ["config"]:
  sys.stdout.write("graph_title CouchDB Availability\n")
  sys.stdout.write("graph_category slycat\n")
  sys.stdout.write("graph_info Tests to see whether the CouchDB server is responding to requests.\n")
  sys.stdout.write("graph_vlabel Availability (%)\n")

  sys.stdout.write("available.label Availability\n")
  sys.stdout.write("available.critical 100:100\n")
else:
  try:
    response = requests.get("http://localhost:5984", proxies={"http":None}).json()
    if response.get("couchdb", None) is None or response.get("version", None) is None:
      raise Exception()
    sys.stdout.write("available.value 100\n")
  except:
    sys.stdout.write("available.value 0\n")

