#!/usr/bin/env python

import requests
import sys

if sys.argv[1:2] == ["config"]:
  print "graph_title CouchDB"
  print "graph_category slycat"
  print "available.label Available"
else:
  try:
    info = requests.get("http://localhost:5984", proxies={"http":None}).json()
    if info.get("couchdb", None) is None or info.get("version", None) is None:
      raise Exception()
    print "available.value 1"
  except:
    print "available.value 0"

