#!/usr/bin/env python

import requests
import sys

def format_value(value, null=0):
  return value if value is not None else null

if sys.argv[1:2] == ["config"]:
  print "graph_title CouchDB Availability"
  print "graph_category slycat"

  print "available.label Available"
  print "available.info Set to 1 if couchdb is responding, otherwise 0."
  print "available.critical 1:1"
else:
  try:
    response = requests.get("http://localhost:5984", proxies={"http":None}).json()
    if response.get("couchdb", None) is None or response.get("version", None) is None:
      raise Exception()
    print "available.value 1"
  except:
    print "available.value 0"

