#!/usr/bin/env python

import os
import requests
import sys

port = os.environ.get("PORT", 443)

if sys.argv[1:2] == ["config"]:
  sys.stdout.write("graph_title Slycat Availability\n")
  sys.stdout.write("graph_category slycat\n")
  sys.stdout.write("graph_info Tests to see whether the Slycat server is responding to requests.\n")
  sys.stdout.write("graph_vlabel Availability (%)\n")

  sys.stdout.write("web_server_available.label Web server availability\n")
  sys.stdout.write("web_server_available.critical 100:100\n")
else:
  try:
    response = requests.get("https://localhost:%s" % port, proxies={"https":None}, verify=False)
    if response.status_code != 200 and response.status_code != 401:
      raise Exception("Unexpected status code: %s" % response.status_code)
    sys.stdout.write("web_server_available.value 100\n")
  except Exception as e:
    sys.stdout.write("web_server_available.value 0\n")

