#!/usr/bin/env python

import re
import subprocess
import sys

if sys.argv[1:2] == ["config"]:
  sys.stdout.write("graph_title Slycat Threads\n")
  sys.stdout.write("graph_category slycat\n")
  sys.stdout.write("graph_info Tracks Slycat Web Server thread count.\n")
  sys.stdout.write("graph_vlabel Number of threads\n")

  sys.stdout.write("web_server_thread_count.label Thread count\n")
else:
  try:
    pid = subprocess.Popen(["pgrep", "-f", "slycat-web-server"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = pid.communicate()
    pid = int(stdout)

    thread_count = open("/proc/%s/status" % pid).read()
    thread_count = int(re.search(r"Threads:\s*(\d*)", thread_count).group(1))

    sys.stdout.write("web_server_thread_count.value %s\n" % (thread_count))

  except Exception as e:
    sys.stdout.write("web_server_thread_count.value U\n")

