#!/usr/bin/env python

import os
import subprocess
import sys

if sys.argv[1:2] == ["config"]:
  sys.stdout.write("graph_title Slycat Requests\n")
  sys.stdout.write("graph_category slycat\n")
  sys.stdout.write("graph_info Tracks Slycat Web Server requests.\n")
  sys.stdout.write("graph_vlabel Requests / Second\n")

  sys.stdout.write("web_server_requests.label Web server requests\n")
  sys.stdout.write("web_server_requests.type DERIVE\n")
else:
  try:
    requests = subprocess.Popen(["wc", "-l", "/var/log/slycat/access.log"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = requests.communicate()
    requests = int(stdout.split()[0])

    sys.stdout.write("web_server_requests.value %s\n" % requests)

  except Exception as e:
    sys.stdout.write("web_server_requests.value U\n")

