#!/usr/bin/env python

import subprocess
import sys

if sys.argv[1:2] == ["config"]:
  sys.stdout.write("graph_title Slycat Files\n")
  sys.stdout.write("graph_category slycat\n")
  sys.stdout.write("graph_info Tracks Slycat Web Server file descriptor count.\n")
  sys.stdout.write("graph_vlabel Count\n")

  sys.stdout.write("web_server_file_count.label Open file descriptors\n")
else:
  try:
    pid = subprocess.Popen(["pgrep", "-f", "slycat-web-server"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = pid.communicate()
    pid = int(stdout)

    pid = subprocess.Popen(["ls", "-l", "/proc/%s/fd" % pid], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = pid.communicate()
    file_count = len(stdout.split("\n"))-2

    sys.stdout.write("web_server_file_count.value %s\n" % (file_count))

  except Exception as e:
    sys.stderr.write("%s\n" % e)
    sys.stdout.write("web_server_file_count.value U\n")

