FROM node:18
# :lts-alpine
# see https://github.com/sass/node-sass/issues/3077 locking down to node 15 until this is resolved
WORKDIR /usr/src/slycat
RUN git config --global http.sslVerify false
RUN git clone --depth 1 https://github.com/sandialabs/slycat.git
WORKDIR /usr/src/slycat/slycat
CMD ls
